@HostAddress = https://localhost:5002
@RiskEndpoint = {{HostAddress}}/risk

@RequestId = 50000000-0000-0000-0000-000000000001
@SafeCustomerId = 00000000-0000-0000-0000-000000000001
@BannedCustomerId = 00000000-0000-0000-0000-000000000002

### 1. ACCEPTANCE TEST
GET {{RiskEndpoint}}?requestId={{RequestId}}&customerId={{SafeCustomerId}}&cost=100.00 HTTP/1.1

### 2. REJECTION TEST: High Cost
GET {{RiskEndpoint}}?requestId={{RequestId}}&customerId={{SafeCustomerId}}&cost=10001.00 HTTP/1.1

### 3. REJECTION TEST: Banned Customer
GET {{RiskEndpoint}}?requestId={{RequestId}}&customerId={{BannedCustomerId}}&cost=500.00 HTTP/1.1